/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dnjndxlngxrnqokcsbpz"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuam5keGxuZ3hybnFva2NzYnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzQ4MzMsImV4cCI6MjA3NDU1MDgzM30.xS3LiQ76sFVllRSOoPsFAEpz4x-hQC3ijJJi8Nt8WTk"
